version: "3.8"

services:
  db:
    image: mongo:5.0.2
    restart: always
    volumes:
      - db:/data/db
    ports:
      - 27017:27017
    mem_limit: 1g

  api:
    build:
      context: .
      target: test
    restart: always
    depends_on:
      - db
    env_file:
      - .test.env
    stdin_open: true
    tty: true
    mem_limit: 1g

volumes:
  db: