version: "3.8"

services:
  db:
    image: mongo:5.0.2
    restart: always
    volumes:
      - db:/data/db
    ports:
      - 27017:27017

  api:
    build: ./
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./tsconfig.json:/home/node/app/tsconfig.json
      - ./src:/home/node/app/src
      - ./node_modules:/home/node/app/node_modules
    ports:
      - 3000:3000
    stdin_open: true
    tty: true

volumes:
  db: