version: "3.8"

services:
  db:
    image: mongo:5.0.2
    restart: always
    volumes:
      - db:/data/db
    ports:
      - 27017:27017

  api:
    build:
      context: .
      target: development
    command: yarn test
    restart: always
    depends_on:
      - db
    env_file:
      - .test.env
    stdin_open: true
    tty: true

volumes:
  db: